// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_AmHHOwh419G56vy2Qsdk9xEQqlpSAyY',
    appId: '1:1037388539528:web:379231de51211067a2613d',
    messagingSenderId: '1037388539528',
    projectId: 'spotify-app-clone-01',
    authDomain: 'spotify-app-clone-01.firebaseapp.com',
    storageBucket: 'spotify-app-clone-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx5RegMWKmXMNNmtiPrMiQYaJ2EoTfL74',
    appId: '1:1037388539528:android:d99fa55eb400d886a2613d',
    messagingSenderId: '1037388539528',
    projectId: 'spotify-app-clone-01',
    storageBucket: 'spotify-app-clone-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOZhcXlsSc0dP5EuqZ_Pc1AmDvAFb7-YQ',
    appId: '1:1037388539528:ios:3a9efe1e20de72e6a2613d',
    messagingSenderId: '1037388539528',
    projectId: 'spotify-app-clone-01',
    storageBucket: 'spotify-app-clone-01.firebasestorage.app',
    iosBundleId: 'com.example.spotifyAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOZhcXlsSc0dP5EuqZ_Pc1AmDvAFb7-YQ',
    appId: '1:1037388539528:ios:3a9efe1e20de72e6a2613d',
    messagingSenderId: '1037388539528',
    projectId: 'spotify-app-clone-01',
    storageBucket: 'spotify-app-clone-01.firebasestorage.app',
    iosBundleId: 'com.example.spotifyAppClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_AmHHOwh419G56vy2Qsdk9xEQqlpSAyY',
    appId: '1:1037388539528:web:6ecc124e28d4fd46a2613d',
    messagingSenderId: '1037388539528',
    projectId: 'spotify-app-clone-01',
    authDomain: 'spotify-app-clone-01.firebaseapp.com',
    storageBucket: 'spotify-app-clone-01.firebasestorage.app',
  );
}
